"""Add alert tables

Revision ID: 107585aa7109
Revises: 001_initial
Create Date: 2025-12-31 15:58:07.235913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '107585aa7109'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.Enum('THRESHOLD_VIOLATION', 'AGENT_INACTIVITY', 'OVERDUE_TASK', 'PENDING_APPROVAL', 'OWNERSHIP_TRANSFER', 'SYSTEM_ERROR', name='alert_rule_type'), nullable=False),
    sa.Column('condition_logic', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=True),
    sa.Column('delivery_channels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_index('idx_alert_rules_active', 'alert_rules', ['is_active'], unique=False)
    op.create_index('idx_alert_rules_type', 'alert_rules', ['rule_type'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('THRESHOLD_VIOLATION', 'AGENT_INACTIVITY', 'OVERDUE_TASK', 'PENDING_APPROVAL', 'OWNERSHIP_TRANSFER', 'SYSTEM_ERROR', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('building_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('alert_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED', name='alert_status'), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('delivery_channels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['agent_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.rule_id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('idx_alerts_agent', 'alerts', ['agent_id'], unique=False)
    op.create_index('idx_alerts_building', 'alerts', ['building_id'], unique=False)
    op.create_index('idx_alerts_created', 'alerts', ['created_at'], unique=False)
    op.create_index('idx_alerts_project', 'alerts', ['project_id'], unique=False)
    op.create_index('idx_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('idx_alerts_type', 'alerts', ['alert_type'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index('idx_alerts_type', table_name='alerts')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.drop_index('idx_alerts_severity', table_name='alerts')
    op.drop_index('idx_alerts_project', table_name='alerts')
    op.drop_index('idx_alerts_created', table_name='alerts')
    op.drop_index('idx_alerts_building', table_name='alerts')
    op.drop_index('idx_alerts_agent', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_alert_rules_type', table_name='alert_rules')
    op.drop_index('idx_alert_rules_active', table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###

